# Generated by Django 4.2.6 on 2023-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_text', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('selo_fonografico', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('pais', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
